version: '5.3'
services:
  bd:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: php
      MYSQL_USER: php
      MYSQL_PASSWORD: 12345
    volumes:
      - ./db/initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    networks:
      - BarFer
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p12345"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: ./web
    container_name: web
    ports:
      - "8080:80"
    depends_on: 
      bd:
        condition: service_healthy
    volumes:
      - ./web/init.sql:/init.sql 
    networks:
      - BarFer
    command: >
      sh -c "
      echo 'Esperando DB...' &&
      until mysql -h bd -u php -p12345 -e 'SELECT 1;' ; do
        sleep 3;
      done &&
      echo 'Ejecutando init.sql desde web...' &&
      mysql -h bd -u php -p12345 php < /init.sql &&
      apache2-foreground
      "

volumes:
  db_data:

networks:
  BarFer:
    driver: bridge
